name: JoinCommand
main: me.kohle.JoinCommand.JoinCommand
version: 1.1-a
author: Kohle
commands:
    hi:
        description: Debug the thing!
        usage: |
            /hi
    jc-reload:
        description: Reloads config.
        usage: |
            /jc-reload