name: JoinCommand
main: me.kohle.JoinCommand.JoinCommand
version: 1.1-d
author: Kohle
commands:
    jc:
        description: Debug the thing!
        usage: |
            /<command>
    jc-reload:
        description: Reloads config.
        usage: |
            /<command>
    jc-addcommand:
        description: Adds a command to config.
        usage: |
            /<command> [listType] [Command]
    jc-ac:
        description: Adds a command to config.
        usage: |
            /<command> [listType] [Command]
permissions:
    JoinCommand.*:
        description: Gives access to all JoindCommand
        children:
            JoinCommand.reload: true
            JoinCommand.FirstCommand: true
            JoinCommand.NormalCommand: true
            JoinCommand.addcommand: true
        default: op
    JoinCommand.reload:
        description: Allows you to reload the config
        default: op
    JoinCommand.addcommand:
        description: Allows you to reload the config
        default: op
    JoinCommand.FirstCommand:
        description: Allows first time command to pass
        default: not op
    JoinCommand.NormalCommand:
        description: Allows every logon command
        default: not op